name: Build and Package Flet Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet flet-cli mysql-connector-python pandas

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Enable Flutter support for Flet
      run: |
        flet enable-flutter

    - name: Build APK
      run: |
        flet pack main.py --target android --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: dist/app-release.apk
