name: Build and Package Flet Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet mysql-connector-python pandas

    - name: Set up Flutter 3.22.2
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.22.2

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses

    - name: Install Android SDK packages
      run: |
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Build APK
      run: |
        # في مشروع Flet، أمر بناء APK هو:
        flet pack apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app-release.apk
